### ISSUE TITLE
4.x - Bake Model getDisplayField() is null

### ISSUE THREAD

**Issue by challgren** [cakephp/bake#572] opened 2019-07-27 12:51 UTC
I have a table that has the following schema

```
CREATE TABLE `ip2_location_db9` (
  `ip_from` int(10) unsigned DEFAULT NULL,
  `ip_to` int(10) unsigned DEFAULT NULL,
  `country_code` char(2) COLLATE utf8_bin DEFAULT NULL,
  `country_name` varchar(64) COLLATE utf8_bin DEFAULT NULL,
  `region_name` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `city_name` varchar(128) COLLATE utf8_bin DEFAULT NULL,
  `latitude` double DEFAULT NULL,
  `longitude` double DEFAULT NULL,
  `zip_code` varchar(30) COLLATE utf8_bin DEFAULT NULL,
  KEY `idx_ip_from` (`ip_from`),
  KEY `idx_ip_to` (`ip_to`),
  KEY `idx_ip_from_to` (`ip_from`,`ip_to`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_bin;
```

When running `bin/cake bake model ip2_location_db9` the following error is outputted

```
Exception: Return value of Bake\Command\ModelCommand::getDisplayField() must be of the type string, null returned in [/Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelCommand.php, line 486]
2019-07-27 07:47:28 Error: [TypeError] Return value of Bake\Command\ModelCommand::getDisplayField() must be of the type string, null returned in /Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelCommand.php on line 486
Stack Trace:
#0 /Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelCommand.php(126): Bake\Command\ModelCommand->getDisplayField(Object(Cake\ORM\Table), Object(Cake\Console\Arguments))
#1 /Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelCommand.php(97): Bake\Command\ModelCommand->getTableContext(Object(Cake\ORM\Table), 'ip2_location_db...', 'Ip2LocationDb9', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#2 /Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelCommand.php(80): Bake\Command\ModelCommand->bake('Ip2LocationDb9', Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#3 /Users/challgren/Projects/avaya4/vendor/cakephp/bake/src/Command/ModelAllCommand.php(80): Bake\Command\ModelCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#4 /Users/challgren/Projects/avaya4/vendor/cakephp/cakephp/src/Console/Command.php(207): Bake\Command\ModelAllCommand->execute(Object(Cake\Console\Arguments), Object(Cake\Console\ConsoleIo))
#5 /Users/challgren/Projects/avaya4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(333): Cake\Console\Command->run(Array, Object(Cake\Console\ConsoleIo))
#6 /Users/challgren/Projects/avaya4/vendor/cakephp/cakephp/src/Console/CommandRunner.php(169): Cake\Console\CommandRunner->runCommand(Object(Bake\Command\ModelAllCommand), Array, Object(Cake\Console\ConsoleIo))
#7 /Users/challgren/Projects/avaya4/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#8 {main}
```

**Comment by ADmad** [comment] 2019-07-27 13:07
When the table doesn't have a `title` or `name` field than the primary key field is used. But you haven't set primary key for the table.

**Comment by ADmad** [comment] 2019-07-27 13:08
While we can throw an better error message from `Table::getDisplayField()` you will have issues with other ORM functions too if your table doesn't have a pK.

**Comment by challgren** [comment] 2019-07-27 13:09
This is a table provided by a 3rd party. There's no primary key because the dataset is over 2 million records and designed to be read only

**Comment by ADmad** [comment] 2019-07-27 13:12
I guess we should make return value of `Table::getDisplayField()` nullable.

**Comment by ADmad** [comment] 2019-07-27 13:18
Err `Table::getDisplayField()` doesn't have a return typehint, so just return typehint of `ModelCommand::getDisplayField()` needs to be updated.

**Comment by saeideng** [comment] 2019-07-27 13:25
it should update to support `null`/`string`/`array`
I can open a PR

**Comment by ADmad** [comment] 2019-07-27 13:26
@saeideng When baking a model with auto detection the return value for `Table::getDisplayField()` can never be array.

**Comment by saeideng** [comment] 2019-07-27 13:28
similar issue https://github.com/cakephp/bake/pull/545

**Comment by ADmad** [comment] 2019-07-27 13:29
But I guess it could be when someone is trying to rebake with existing class for table. In which case the `table.twig` would also need to be updated to account for display field being array. Currently it assumes it will be either string or empty.

**Comment by ADmad** [comment] 2019-07-27 13:29
Closing as duplicate of #545.

**Closed by ADmad** 2019-07-27 13:29 UTC
Labels: Defect
