### ISSUE TITLE
Unknown command cake bake

### ISSUE THREAD

**Issue by Armando687** [cakephp/bake#458] opened 2018-07-24 00:43 UTC
Tengo problemas al crear el model  con bin/cake  bake nombre 
Me sale : 
Exception: unknown command 'cake bake ' . Run cake -- help  to get the list of valid commands in /var/www/html/congress/vendor/cakephp/cakephp/src/console/CommandRunner.php line 321

**Comment by markstory** [comment] 2018-07-24 01:41
Have you ensured that bake is installed? Try running `composer require cakephp/bake` which will install bake.

**Comment by Armando687** [comment] 2018-07-24 01:55
En un princio bin/cake bake  model funcionaba correctamente. Solo que  tube que hacer algunos cambios en la base de datos. Y ahora pretendo remodelar con bake model para que se se modele los cambios de la base de datos. Pero ahora me sale ese error  y no entiendo el problema ya que no reconoce el comando ya intente el composer update composer install y nada

**Comment by dereuromark** [comment] 2018-08-17 11:42
You need to run `bin/cake ...`
This is not a bug of the plugin, but a user error. Closing as such. 

If you are
looking for help on how to implement a feature or to better understand
how to use the framework correctly, please visit one of the following:

[The CakePHP Manual](https://book.cakephp.org)
[The CakePHP online API](https://api.cakephp.org)
[The CakePHP Forum](https://discourse.cakephp.org) 
[Stackoverflow](https://stackoverflow.com/questions/tagged/cakephp)

or the #cakephp channel on irc.freenode.net, where we will be more than
happy to help answer your questions.

Thanks!

**Closed by dereuromark** 2018-08-17 11:42 UTC

**Comment by ADmad** [comment] 2018-08-24 11:37
I just did a test using latest app skeleton installing it using `composer create-project cakephp/app myapp`.

After that running `bin/cake bake` from the folder gives me expected output:
```
The following commands can be used to generate skeleton code for your application.

Available bake commands:

- all
- behavior
- cell
- command
- component
- controller
- fixture
- form
- helper
- mailer
- middleware
- migration
- migration_diff
- migration_snapshot
- model
- plugin
- seed
- shell
- shell_helper
- task
- template
- test
- twig_template

By using `cake bake [name]` you can invoke a specific bake task.
```

**Comment by davidxwheatley** [comment] 2018-09-08 12:08
Experiencing same problem
Updated CakePHP 3.6.11. From CakePHP 3.5.*. using composer update.
Installed as expected no errors.

bin/cake **bake** .... Not available:
**ERROR:** _Exception: Unknown command `cake bake`. Run `cake --help` to get the list of valid commands_.

bin/cake -h

Available Commands:
- cache
- completion
- console
- help
- i18n
- orm_cache
- plugin
- routes
- schema_cache
- server
- version

**Comment by davidxwheatley** [comment] 2018-09-08 12:30
UPDATE - **Using ADmad suggestion above** - Created a new project from scratch composer create-project cakephp/app myapp ...  this worked bin/cake bake is available.

**Comment by dereuromark** [comment] 2018-09-08 12:32
Make sure the plugin is installed via composer and loaded properly as documented.
Then it will also work for upgraded apps.

**Comment by davidxwheatley** [comment] 2018-09-08 12:35
Cheers Mark .... Appreciate quick response.

**Comment by Back-Sephiroth** [comment] 2019-03-04 10:26
Hello,

I have the same problem, and i can't find how resolve this one.

When i run cake --help => bake isn't displayed

i've tried remove and required the composer command and this not resolved the problem.

Have you any other suggestions ?

thanks

**Comment by dereuromark** [comment] 2019-03-04 10:27
Did u load the plugin as documented? e.g. in Application.php?

**Comment by Back-Sephiroth** [comment] 2019-03-04 10:32
no, i don't, 

Where it is documented, because in other project, i haven't need to configure it.

**Comment by Back-Sephiroth** [comment] 2019-03-04 10:40
i found the solution after create a new project, the Application.php file : 


```
public function bootstrap()
    {
        // Call parent to load bootstrap from files.
        parent::bootstrap();

        if (PHP_SAPI === 'cli') {
            try {
                $this->addPlugin('Bake');
            } catch (MissingPluginException $e) {
                // Do not halt if the plugin is missing
            }

            $this->addPlugin('Migrations');
        }

        /*
         * Only try to load DebugKit in development mode
         * Debug Kit should not be installed on a production system
         */
        if (Configure::read('debug')) {
            $this->addPlugin(\DebugKit\Plugin::class);
        }
    }
```

This code doesn't exists in my project, so when i duplicate it, the problem is resolved.

Thanks for your help.

Regards.
