### ISSUE TITLE
Ignore created/modified value changes when re-baking models?

### ISSUE THREAD

**Issue by mehov** [cakephp/bake#770] opened 2021-09-30 18:24 UTC
Hi everyone,

Here's my workflow with one test application:

- Design the database schema using the visual diagram tool in MySQL Workbench; synchronise it with the live database
- Bake models
- Commit the files
- Make further changes to that local schema and synchronise those
- Re-bake the models
- Commit the changes to those files, skipping the values for `created` and `modified`

Is there any way to tell bake to ignore the changes to the datetime values? This way I don't have to manually unstage them every time

**Comment by dereuromark** [comment] 2022-03-08 17:38
Re-baking by design always overwrites, it cannot see or look into those files.
This would require some more high level logic on top that is as of right now most likely out of scope.

**Comment by dereuromark** [comment] 2022-03-08 17:38
Refs https://github.com/cakephp/bake/issues/651

**Closed as completed** 2022-03-09 06:03 UTC
Labels: question
