### ISSUE TITLE
bake plugin - autoload issues

### ISSUE THREAD

**Issue by xrep** [cakephp/bake#291] opened 2016-12-26 12:36 UTC
Hello, 

I've just tried to create my own plugin as described in [official documentation](http://book.cakephp.org/3.0/en/plugins.html#plugin-configuration)  through 
`bin/cake bake plugin Admin`

created "DashboardController" in related directory and when approached
`mysite.dev/admin/dashboard`

there was an "Missing Controller" Exception, that was saying that my "DashboardController" did not exist. 

Docu says:

> When using bake for creating a plugin or when installing a plugin using Composer, you don’t typically need to make any changes to your application in order to make CakePHP recognize the classes that live inside it.

This class wasn't properly loaded through autoload and even if existed there was misleading error screen. 

I was able to fix this issue through 2 ways:

a.)
edit main "composer.json"  in application root.  
i've added `"Admin\\": "./plugins/Admin/src"` into following section:
```
"autoload": {
        "psr-4": {
            "App\\": "src",
            "Admin\\": "./plugins/Admin/src"
        }
    },
```

b.) in application bootstrap.php when loading plugin add "autoload => true" param in Plugin::load method. 

`Plugin::load( 'Admin', ['bootstrap' => false, 'routes' => true, 'autoload' => true ]);`

otherwise Cake wasnt able recognize my plugin classes.

**Comment by markstory** [comment] 2016-12-26 15:51
Bake should have updated your application's composer.json file. I'll see if I can reproduce this.

**Comment by markstory** [comment] 2016-12-26 17:05
I just tried running bake locally, and my application's `composer.json` was updated correctly

```bash
$ bin/cake bake plugin BakedPlugin

Welcome to CakePHP v3.3.10 Console
---------------------------------------------------------------
App : src
Path: /Users/markstory/Sites/cakephp-app/src/
PHP : 7.1.0RC6
---------------------------------------------------------------
Plugin Name: BakedPlugin
Plugin Directory: /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin
---------------------------------------------------------------
Look okay? (y/n/q)
[y] > y
Generating README.md file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/README.md
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/README.md`
Generating composer.json file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/composer.json
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/composer.json`
Generating config/routes.php file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/config/routes.php
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/config/routes.php`
Generating phpunit.xml.dist file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/phpunit.xml.dist
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/phpunit.xml.dist`
Generating src/Controller/AppController.php file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/src/Controller/AppController.php
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/src/Controller/AppController.php`
Generating webroot/empty file...

Creating file /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/webroot/empty
Wrote `/Users/markstory/Sites/cakephp-app/plugins/BakedPlugin/webroot/empty`
Modifying composer autoloader

File `/Users/markstory/Sites/cakephp-app/composer.json` exists
Do you want to overwrite? (y/n/a/q)
[n] > y
Wrote `/Users/markstory/Sites/cakephp-app/composer.json`


/Users/markstory/Sites/cakephp-app/config/bootstrap.php modified
---------------------------------------------------------------
Created: BakedPlugin in /Users/markstory/Sites/cakephp-app/plugins/BakedPlugin

Deleted `/Users/markstory/Sites/cakephp-app/plugins/empty`
```

The changes to my composer.json were:

```diff
$ git diff composer.json
diff --git a/composer.json b/composer.json
index 79b3e8d..87ce489 100644
--- a/composer.json
+++ b/composer.json
@@ -23,13 +23,15 @@
     },
     "autoload": {
         "psr-4": {
-            "App\\": "src"
+            "App\\": "src",
+            "BakedPlugin\\": "./plugins/BakedPlugin/src"
         }
     },
     "autoload-dev": {
         "psr-4": {
             "App\\Test\\": "tests",
-            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
+            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests",
+            "BakedPlugin\\Test\\": "./plugins/BakedPlugin/tests"
         }
     },
     "scripts": {
```

And the contents `vendor/composer/autoload_psr4.php` were also updated meaning that `composer dumpautoload` was run. Is it possible that bake could not find your composer installation? If so you can use the `--composer` option to tell bake where it can find composer.

As it stands right now, I'm not able to reproduce the issue you were having.

**Comment by xrep** [comment] 2016-12-26 17:50
hello  markstory, 

thanks for your effort. Now i can see what when wrong, 

when running 

`bin/cake bake plugin BakedPlugin`

i just pressed "Enter" so my main composer.json wasn't overwritten as the default option is not rewriting composer.json

**Comment by markstory** [comment] 2016-12-26 23:30
Overwriting a file always defaults to no in bake, as it helps prevent files accidentally being overwritten. I'm going to close this as it sounds like a prompt was missed, and I don't think changing the defaults is worth the break in consistency.

**Closed by markstory** 2016-12-26 23:30 UTC
Labels: bug, On Hold
