### ISSUE TITLE
Error bake seed

### ISSUE THREAD

**Issue by Ashrafdev** [cakephp/bake#354] opened 2017-08-05 12:11 UTC
![image](https://user-images.githubusercontent.com/14801084/28995368-294fb9aa-7a1a-11e7-8dd7-e88aa1430656.png)

- fresh install cakephp 3

**Comment by Ashrafdev** [comment] 2017-08-05 12:12
you can try after fresh install cakephp 3 and bake seed .

**Comment by ADmad** [comment] 2017-08-05 12:15
Duplicate of #353

**Closed by ADmad** 2017-08-05 12:15 UTC

**Comment by HavokInspiration** [comment] 2017-08-05 13:19
The relevant PR has been merged a new release of migrations plugin have been made. This should be fixed now.
