### ISSUE TITLE
[CakePHP 4.x] Bake migration_diff throws errors

### ISSUE THREAD

**Issue by Rindula** [cakephp/bake#664] opened 2020-03-24 08:52 UTC
When running `bin/cake bake migration_diff Test` with active Database changes the following an Error occures. Since the log is short, here is the complete log (with censored paths):

```log
Creating file C:\Path\To\Project\config\Migrations\20200324084537_Test.php
Wrote `C:\Path\To\Project\config\Migrations\20200324084537_Test.php`
Marking the migration 20200324084537_Test as migrated...
Exception: Shell class for "Migrations" could not be found. If you are trying to use a plugin shell, that was loaded via $this->add
Plugin(), you may need to update bin/cake.php to match https://github.com/cakephp/app/tree/master/bin/cake.php
In [C:\Path\To\Project\vendor\cakephp\cakephp\src\Console\ShellDispatcher.php, line 332]
```

Its a fresh CakePHP 4 Project with everything up to date. (Just ran `composer update`)

If I comment out the Mark Migration command Executor in the command, it throws its next error at the database schema dump creation.

**Comment by ADmad** [comment] 2020-03-24 09:08
Duplicate of https://github.com/cakephp/migrations/pull/435

**Closed by ADmad** 2020-03-24 09:08 UTC
