### ISSUE TITLE
Baked _indexes with MySQL

### ISSUE THREAD

**Issue by steefaan** [cakephp/bake#169] opened 2015-10-26 15:15 UTC
It seems that MySQL isn't able to create foreign keys without indexes, sqlite and postgres don't need these indexes... if I bake a fixture from a MySQL table it will create `_indexes` and `_constraints`... if I run test cases on MySQL everything works fine but if I run test cases with postgres or sqlite and I have two fixtures with same _indexes it will fail with `Warning Error: Fixture creation for "threads" failed "SQLSTATE[HY000]: General error: 1 index user_id already exists" in [/var/www/project/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php, line 240]`

If I bake the fixtures from Postgres everything works fine.

This issue is related to https://github.com/cakephp/cakephp/issues/7608. In my opinion it's an issue with bake.

**Comment by markstory** [comment] 2015-10-26 16:06
I bet we shouldn't have the duplicate index attributes. Creating a constraint also creates an index in mysql.

**Comment by steefaan** [comment] 2015-10-26 16:24
@markstory Yes creating a contraint creates also an index. Don't create the index in the fixture when a constraint exists should solve this issue.

**Comment by markstory** [comment] 2015-10-27 01:10
I wasn't able to reproduce this issue. The following table definition which includes constraints and indexes doesn't have any duplication issues:

```sql
CREATE TABLE `bookmarks_tags` (
  `bookmark_id` int(11) NOT NULL,
  `tag_id` int(11) NOT NULL,
  `starred` tinyint(1) DEFAULT '0',
  PRIMARY KEY (`bookmark_id`,`tag_id`),
  KEY `tag_idx` (`tag_id`,`bookmark_id`),
  CONSTRAINT `bookmarks_tags_ibfk_1` FOREIGN KEY (`tag_id`) REFERENCES `tags` (`id`),
  CONSTRAINT `bookmarks_tags_ibfk_2` FOREIGN KEY (`bookmark_id`) REFERENCES `bookmarks` (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8
```

What does your threads table create statement look like?

**Comment by markstory** [comment] 2015-10-27 01:11
I tested with PHP 5.5.27 and MySQL 5.6.20

**Comment by steefaan** [comment] 2015-10-27 09:15
This is how my migration file looks like:

```
$this->table('threads', ['id' => false, 'primary_key' => 'id', 'collation' => 'utf8_unicode_ci'])
            ->addColumn('id', 'uuid')
            ->addColumn('user_id', 'uuid')
            ->addColumn('category_id', 'uuid')
            ->addColumn('name', 'string', ['limit' => 1024])
            ->addColumn('description', 'text')
            ->addColumn('type', 'integer', ['limit' => MysqlAdapter::INT_TINY, 'signed' => false])
            ->addColumn('price', 'float', ['default' => null, 'null' => true, 'signed' => false])
            ->addColumn('coupon_code', 'string', ['limit' => 128, 'default' => null, 'null' => true])
            ->addColumn('affiliate_link', 'string', ['limit' => 2048, 'default' => null, 'null' => true])
            ->addColumn('minimum_order_value', 'float', ['default' => null, 'null' => true, 'signed' => false])
            ->addColumn('availability', 'integer', ['limit' => MysqlAdapter::INT_TINY, 'signed' => false, 'default' => null, 'null' => true])
            ->addColumn('approved', 'boolean', ['signed' => false, 'default' => false])
            ->addColumn('expires', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('deleted', 'datetime', ['default' => null, 'null' => true])
            ->addColumn('modified', 'datetime')
            ->addColumn('created', 'datetime')
            ->addForeignKey('user_id', 'users', 'id', ['delete' => 'CASCADE', 'update' => 'CASCADE'])
            ->addForeignKey('category_id', 'categories', 'id', ['delete' => 'CASCADE', 'update' => 'CASCADE'])
            ->create();
```

The migration file works for every database (Postgres, SQLite, MySQL). If I bake the fixture for threads from MySQL it will create `_indexes` and `_constraints` in the fixture.

**Comment by markstory** [comment] 2015-10-28 01:05
I bet the mysql phinx driver is creating a redundant index as per the related cakephp/cakephp issue. Closing as the schema reflection is behaving as it should and this issue is caused by index names overlapping with coulmn names.

**Closed by markstory** 2015-10-28 01:05 UTC
Labels: bug

**Comment by HavokInspiration** [comment] 2015-10-28 07:57
Yes, adding the index manually in your migrations with unique names accross your different tables should prevent that from happening.

**Comment by steefaan** [comment] 2015-10-28 09:16
@markstory But MySQL needs an index on the field before you're able to create the foreign key between two tables. Postgres doesn't need this index. You can try this with phpmyadmin for MySQL or Adminer for MySQL/Postgres.

**Comment by markstory** [comment] 2015-10-28 13:58
@steefaan MySQL does not need an index on a field to add a foreign key.

```sql
root@test> create table articles ( id integer primary key auto_increment not null, title varchar(255), body text, created datetime, modified datetime );
Query OK, 0 rows affected (0.01 sec)

root@test> create table comments (id integer primary key auto_increment not null, article_id integer, body text, created datetime, modified datetime);
Query OK, 0 rows affected (0.01 sec)

root@test> alter table comments add constraint `comments_article_idx` foreign key (article_id) references articles(id);
Query OK, 0 rows affected (0.04 sec)
Records: 0  Duplicates: 0  Warnings: 0
```
