### ISSUE TITLE
If you create an entity with `bin/cake bake model`, the Value of `$_accessible` is generated with "1".  I want boolean.

### ISSUE THREAD

**Issue by yuki-yasumura** [cakephp/bake#820] opened 2022-04-11 08:32 UTC
### Description

ex

```sh
$ bin/cake bake model users
```

```php
class User extends Entity
{
    // ...
    protected $_accessible = [
        'id' => 1,
        'email' => 1,
        'password' => 1,
    ];
    // ...
}
```

Here's what I want.
```
class User extends Entity
{
    // ...
    protected $_accessible = [
        'id' => true,
        'email' => true,
        'password' => true,
    ];
    // ...
}
```

### CakePHP Version

4.3.0

### PHP Version

8.0

**Comment by saeideng** [comment] 2022-04-13 09:32
I could not reproduce the issue

**Comment by saeideng** [comment] 2022-04-13 10:26
I tested it with mysql DB
did you test in fresh installation?

**Comment by yuki-yasumura** [comment] 2022-04-14 03:10
I use postgresql.

May I see the Entity created by bin/cake bake?

**Comment by saeideng** [comment] 2022-04-14 07:11
> May I see the Entity created by bin/cake bake?

```php
    protected $_accessible = [
        'username' => true,
        'password' => true,
    ];
```

mysql
cakephp/cakephp | 4.3.7
cakephp/bake | 2.6.1

**Comment by othercorey** [comment] 2022-04-14 14:17
Can you show us the table schema for id, email and password? Which version of postgresql?

**Comment by Mr-IjIj** [comment] 2022-04-16 14:07
Sorry for the late reply.

I have renewed my environment and checked again and found that `$_accessible` in both mysql and postgresql created an entity with boolean.

It appears that I was wrong about myself prematurely.

I will do some more research on Monday.
`bin/cake bake` seems to work fine.
Perhaps some package is doing something wrong.

I'm sorry for troubling you.

**Comment by Mr-IjIj** [comment] 2022-04-16 14:10
I will close this issue once.

**Comment by Mr-IjIj** [comment] 2022-04-16 14:24
My `cake/bake` version is  "2.6.1".

**Comment by yuki-yasumura** [comment] 2022-04-16 15:26
@saeideng @othercorey 

Sorry for the late reply.
My version and detail info
```
cakephp/cakephp | 4.3.7
cakephp/bake | 2.6.1

postgresql 13.5
schema null
```

But,
I have renewed my environment and checked again and found that $_accessible in both mysql and postgresql created an entity with boolean.
It appears that I was wrong about myself prematurely.
I will do some more research on Monday.
bin/cake bake seems to work fine.
Perhaps some package is doing something wrong.
I’m sorry for troubling you.


I will close this issue once.

**Closed as completed** 2022-04-16 15:36 UTC
Labels: defect
