### ISSUE TITLE
Can't bake simple view template  cakephp 4 

### ISSUE THREAD

**Issue by simodaya** [cakephp/bake#711] opened 2020-10-11 05:52 UTC
( macOS Catalina / PHP 7.4.11 / Homebrew and intl installed / MAMP )

1 - `./cake bake controller users` : It worked for me and display data from database with view function from UsersController created with bake.

but when i do

2 : `./cake bake template users` or `./cake bake model users`

I get this error : `Connection to Mysql could not be established: SQLSTATE[HY000] [2002] No such file or directory`

3 : when i try : `./cake bake template all` or `./cake bake model all`

Exception: Connection to Mysql could not be established: SQLSTATE[HY000] [2002] No such file or directory In [/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Driver.php, line 107]

Error: [Cake\Database\Exception\MissingConnectionException] Connection to Mysql could not be established: SQLSTATE[HY000] [2002] No such file or directory in /Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Driver.php on line 107 Exception Attributes: array ( 'driver' => 'Mysql', 'reason' => 'SQLSTATE[HY000] [2002] No such file or directory', ) Stack Trace:

/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php:114
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Schema/BaseSchema.php:47
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Dialect/MysqlDialectTrait.php:65
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:53
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Database/Connection.php:400
/Applications/MAMP/htdocs/cake4/vendor/cakephp/bake/src/Utility/TableScanner.php:65
/Applications/MAMP/htdocs/cake4/vendor/cakephp/bake/src/Utility/TableScanner.php:82
/Applications/MAMP/htdocs/cake4/vendor/cakephp/bake/src/Command/TemplateAllCommand.php:60
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Console/BaseCommand.php:175
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Console/CommandRunner.php:336
/Applications/MAMP/htdocs/cake4/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171
/Applications/MAMP/htdocs/cake4/bin/cake.php:12

PS : A already added `export PATH=/Applications/MAMP/bin/php/php7.4.11/bin:$PATH` to `~/.bash_profile`

Same error on CakePHP3, any help please ???

**Comment by othercorey** [comment] 2020-10-11 06:00
Looks like you don't have a valid default connection setup in your app config.

**Comment by simodaya** [comment] 2020-10-12 01:29
CakePHP Homepage : Database => CakePHP is able to connect to the database.
After controllers created Databases data displays using view function with JSON.

**Comment by markstory** [comment] 2020-10-12 01:32
It is likely that your CLI PHP runtime differs from the PHP runtime your webserver is using. Ensure that on the cli you have the correct version `php -v` and that you have the mysql extensions loaded `php -m | grep -i mysql`

**Comment by simodaya** [comment] 2020-10-12 01:37
Thank you, i'll try it now

**Comment by simodaya** [comment] 2020-10-12 01:37
`php -v`
PHP 7.4.11 (cli) (built: Oct  1 2020 23:30:54) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.11, Copyright (c), by Zend Technologies

`php -m | grep -i mysql`
mysqli
mysqlnd
pdo_mysql

**Comment by othercorey** [comment] 2020-10-12 05:13
Your error indicates it's trying to connect to mysql through socket connection. Perhaps your mysql instance isn't running on your local machine.

**Comment by simodaya** [comment] 2020-10-12 11:00
`sudo /usr/local/mysql/support-files/mysql.server start`
Password:
Starting MySQL
.Logging to '/usr/local/mysql/data/192.168.0.108.err'.
.................................................................................................... ERROR! The server quit without updating PID file (/usr/local/mysql/data/192.168.0.108.pid).

How can i fix it ??

**Comment by markstory** [comment] 2020-10-12 14:42
Are you able to connect to mysql from a simple php script that you run on the command line?

**Comment by othercorey** [comment] 2020-10-12 20:01
You will get more help if you use the slack channel or https://discourse.cakephp.org/ forum.

**Comment by simodaya** [comment] 2020-10-13 23:26
@markstory good idea thank you, i'll try !!

**Comment by simodaya** [comment] 2020-10-13 23:43
php test.php
PHP Warning:  mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in /Users/macbook/Desktop/test.php on line 13

Warning: mysqli_connect(): (HY000/1045): Access denied for user 'root'@'localhost' (using password: YES) in /Users/macbook/Desktop/test.php on line 13

**Comment by markstory** [comment] 2020-10-14 01:24
Ok. So until that works, CakePHP doesn't have a chance. You should also try `root@127.0.0.1` as depending on configuration localhost doesn't always work.

**Comment by dereuromark** [comment] 2020-10-19 12:56
This is a user error, not a bug. Closing then.

**Closed by dereuromark** 2020-10-19 12:56 UTC
Labels: question
