### ISSUE TITLE
Twig is crashing when I try to bake a controller

### ISSUE THREAD

**Issue by keomaborges** [cakephp/bake#381] opened 2017-11-24 16:08 UTC
I just updated bake from 1.5.3 to 1.5.4 and I can't bake controllers no more. This is what is happening:

```
keoma@vbox:~/projetos/cdl$ bin/cake bake controller parties

Baking controller class for Parties...
Exception: Unexpected "element" tag (expecting closing tag for the "for" tag defined near line 55) in "/home/keoma/projetos/cdl/vendor/cakephp/bake/src/Template/Bake/Controller/controller.twig" at line 55. in [/home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Parser.php, line 175]
2017-11-24 15:56:31 Error: [Twig_Error_Syntax] Unexpected "element" tag (expecting closing tag for the "for" tag defined near line 55) in "/home/keoma/projetos/cdl/vendor/cakephp/bake/src/Template/Bake/Controller/controller.twig" at line 55. in /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Parser.php on line 175
Stack Trace:
#0 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/TokenParser/For.php(42): Twig_Parser->subparse(Array)
#1 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Parser.php(190): Twig_TokenParser_For->parse(Object(Twig_Token))
#2 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Parser.php(103): Twig_Parser->subparse(NULL, false)
#3 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Environment.php(712): Twig_Parser->parse(Object(Twig_TokenStream))
#4 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Environment.php(770): Twig_Environment->parse(Object(Twig_TokenStream))
#5 /home/keoma/projetos/cdl/vendor/twig/twig/lib/Twig/Environment.php(452): Twig_Environment->compileSource(Object(Twig_Source))
#6 /home/keoma/projetos/cdl/vendor/wyrihaximus/twig-view/src/View/TwigView.php(178): Twig_Environment->loadTemplate('/home/keoma/pro...')
#7 /home/keoma/projetos/cdl/vendor/cakephp/bake/src/View/BakeView.php(139): WyriHaximus\TwigView\View\TwigView->_render('/home/keoma/pro...')
#8 /home/keoma/projetos/cdl/vendor/cakephp/bake/src/Shell/Task/BakeTemplateTask.php(89): Bake\View\BakeView->render('Controller/cont...')
#9 /home/keoma/projetos/cdl/vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(190): Bake\Shell\Task\BakeTemplateTask->generate('Controller/cont...')
#10 /home/keoma/projetos/cdl/vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(162): Bake\Shell\Task\ControllerTask->bakeController('Parties', Array)
#11 /home/keoma/projetos/cdl/vendor/cakephp/bake/src/Shell/Task/ControllerTask.php(69): Bake\Shell\Task\ControllerTask->bake('Parties')
#12 /home/keoma/projetos/cdl/vendor/cakephp/cakephp/src/Console/Shell.php(507): Bake\Shell\Task\ControllerTask->main('parties')
#13 /home/keoma/projetos/cdl/vendor/cakephp/cakephp/src/Console/Shell.php(500): Cake\Console\Shell->runCommand(Array, false, Array)
#14 /home/keoma/projetos/cdl/vendor/cakephp/cakephp/src/Console/CommandRunner.php(141): Cake\Console\Shell->runCommand(Array, true)
#15 /home/keoma/projetos/cdl/bin/cake.php(12): Cake\Console\CommandRunner->run(Array)
#16 {main}
```

This is my composer.json:

```
{
    "name": "cakephp/app",
    "description": "CakePHP skeleton app",
    "homepage": "https://cakephp.org",
    "type": "project",
    "license": "MIT",
    "require": {
        "php": ">=5.6",
        "cakephp/cakephp": "3.5.*",
        "mobiledetect/mobiledetectlib": "2.*",
        "cakephp/migrations": "~1.0",
        "cakephp/plugin-installer": "~1.0",
        "josegonzalez/dotenv": "2.*",
        "narendravaghela/cakephp-mailgun": "^1.0",
        "fzaninotto/faker": "^1.7"
    },
    "require-dev": {
        "psy/psysh": "@stable",
        "cakephp/debug_kit": "~3.2",
        "cakephp/bake": "~1.1",
        "cakephp/cakephp-codesniffer": "^3.0"
    },
    "suggest": {
        "markstory/asset_compress": "An asset compression plugin which provides file concatenation and a flexible filter system for preprocessing and minification.",
        "dereuromark/cakephp-ide-helper": "After baking your code, this keeps your annotations in sync with the code evolving from there on for maximum IDE and PHPStan compatibility.",
        "phpunit/phpunit": "Allows automated tests to be run without system-wide install.",
        "cakephp/cakephp-codesniffer": "Allows to check the code against the coding standards used in CakePHP."
    },
    "autoload": {
        "psr-4": {
            "App\\": "src"
        }
    },
    "autoload-dev": {
        "psr-4": {
            "App\\Test\\": "tests",
            "Cake\\Test\\": "./vendor/cakephp/cakephp/tests"
        }
    },
    "scripts": {
        "post-install-cmd": "App\\Console\\Installer::postInstall",
        "post-create-project-cmd": "App\\Console\\Installer::postInstall",
        "post-autoload-dump": "Cake\\Composer\\Installer\\PluginInstaller::postAutoloadDump",
        "check": [
            "@test",
            "@cs-check"
        ],
        "cs-check": "phpcs --colors -p --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "cs-fix": "phpcbf --colors --standard=vendor/cakephp/cakephp-codesniffer/CakePHP ./src ./tests",
        "test": "phpunit --colors=always"
    },
    "prefer-stable": true
}
```

I don't know if it's a Bake or Twig issue. I'm considering Bake because it happened just after I update Bake using `composer update`. I'm developing on Ubuntu 16.04 and Apache2 as server.

**Comment by ADmad** [comment] 2017-11-24 17:05
There hasn't been any change since 1.5.3 which would cause this issue. I tested using latest skeleton app which pulled in 1.5.4 and baking controller worked without issue.

**Comment by keomaborges** [comment] 2017-11-24 17:11
I tested with a fresh cakephp instalation too and I could bake controllers with no problems. This is strange, how could it happened?

**Comment by saeideng** [comment] 2017-11-24 22:08
remove cache

**Comment by keomaborges** [comment] 2017-11-24 23:00
I've already tried this. No success.

**Comment by markstory** [comment] 2017-11-25 01:26
What version of TwigView do you have installed @keomaborges ?

**Comment by keomaborges** [comment] 2017-11-25 02:02
@markstory According Twig's changelog, it's 1.35.0.

**Comment by markstory** [comment] 2017-11-25 02:34
No I meant the twig plugin. Perhaps include the output of `composer show`?

**Comment by ADmad** [comment] 2017-11-25 04:48
Try running `composer update cakephp/bake --with-dependencies`

**Comment by keomaborges** [comment] 2017-11-27 17:40
@markstory 

```
keoma@vbox:~/projetos/cdl$ composer show
ajgl/breakpoint-twig-extension        0.3.1   Twig extension to set breakpo...
aptoma/twig-markdown                  2.0.0   Twig extension to work with M...
asm89/twig-cache-extension            1.3.2   Cache fragments of templates ...
aura/intl                             3.0.0   The Aura Intl package provide...
cakephp/bake                          1.5.4   Bake plugin for CakePHP 3
cakephp/cakephp                       3.5.6   The CakePHP framework
cakephp/cakephp-codesniffer           3.0.1   CakePHP CodeSniffer Standards
cakephp/chronos                       1.1.2   A simple API extension for Da...
cakephp/debug_kit                     3.11.1  CakePHP Debug Kit
cakephp/migrations                    1.7.1   Database Migration plugin for...
cakephp/plugin-installer              1.0.0   A composer installer for Cake...
clue/stream-filter                    v1.4.0  A simple and modern approach ...
composer/ca-bundle                    1.0.9   Lets you find a path to the s...
composer/composer                     1.5.2   Composer helps you declare, m...
composer/semver                       1.4.2   Semver library that offers ut...
composer/spdx-licenses                1.1.6   SPDX licenses list and valida...
dnoegel/php-xdg-base-dir              0.1     implementation of xdg base di...
fzaninotto/faker                      v1.7.1  Faker is a PHP library that g...
guzzlehttp/guzzle                     6.3.0   Guzzle is a PHP HTTP client l...
guzzlehttp/promises                   v1.3.1  Guzzle promises library
guzzlehttp/psr7                       1.4.2   PSR-7 message implementation ...
jakub-onderka/php-console-color       0.1    
jakub-onderka/php-console-highlighter v0.3.2 
jasny/twig-extensions                 v1.2.0  A set of useful Twig filters
jdorn/sql-formatter                   v1.2.17 a PHP SQL highlighting library
josegonzalez/dotenv                   2.1.0   dotenv file parsing for PHP
justinrainbow/json-schema             5.2.6   A library to validate a json ...
m1/env                                2.1.0   Env is a lightweight library ...
mailgun/mailgun-php                   2.3.4   The Mailgun SDK provides meth...
mobiledetect/mobiledetectlib          2.8.26  Mobile_Detect is a lightweigh...
narendravaghela/cakephp-mailgun       v1.0.5  MailgunEmail plugin for CakePHP
nikic/php-parser                      v3.1.2  A PHP parser written in PHP
php-http/client-common                v1.6.0  Common HTTP Client implementa...
php-http/discovery                    1.3.0   Finds installed HTTPlug imple...
php-http/guzzle6-adapter              v1.1.1  Guzzle 6 HTTP Adapter
php-http/httplug                      v1.1.0  HTTPlug, the HTTP client abst...
php-http/message                      1.6.0   HTTP Message related tools
php-http/message-factory              v1.0.2  Factory interfaces for PSR-7 ...
php-http/multipart-stream-builder     1.0.0   A builder class that help you...
php-http/promise                      v1.0.0  Promise used for asynchronous...
psr/http-message                      1.0.1   Common interface for HTTP mes...
psr/log                               1.0.2   Common interface for logging ...
psy/psysh                             v0.8.15 An interactive shell for mode...
robmorgan/phinx                       v0.8.1  Phinx makes it ridiculously e...
seld/cli-prompt                       1.0.3   Allows you to prompt for user...
seld/jsonlint                         1.6.1   JSON Linter
seld/phar-utils                       1.0.1   PHAR file format utilities, f...
squizlabs/php_codesniffer             3.1.1   PHP_CodeSniffer tokenizes PHP...
symfony/config                        v3.3.13 Symfony Config Component
symfony/console                       v3.3.13 Symfony Console Component
symfony/debug                         v3.3.13 Symfony Debug Component
symfony/filesystem                    v3.3.13 Symfony Filesystem Component
symfony/finder                        v3.3.13 Symfony Finder Component
symfony/options-resolver              v3.3.13 Symfony OptionsResolver Compo...
symfony/polyfill-mbstring             v1.6.0  Symfony polyfill for the Mbst...
symfony/process                       v3.3.13 Symfony Process Component
symfony/var-dumper                    v3.3.13 Symfony mechanism for explori...
symfony/yaml                          v3.3.13 Symfony Yaml Component
twig/twig                             v1.35.0 Twig, the flexible, fast, and...
umpirsky/twig-php-function            v0.1    Call (almost) any PHP functio...
webmozart/assert                      1.2.0   Assertions to validate method...
wyrihaximus/twig-view                 4.1.0   Twig powered View for CakePHP3
zendframework/zend-diactoros          1.6.1   PSR HTTP Message implementations

```

@ADmad I ran the command but the issue persists.

**Comment by Jonatanmdez** [comment] 2017-12-05 08:36
Same problem :( 

```
Unexpected "element" tag (expecting closing tag for the "for" tag defined near line 55) in "/var/www/html/dashboard/vendor/cakephp/bake/src/Template/Bake/Controller/controller.twig" at line 55. in [/var/www/html/dashboard/vendor/twig/twig/lib/Twig/Parser.php, line 175]
```

**Comment by Jonatanmdez** [comment] 2017-12-05 08:42
I tried with php5.6, php 7.0 and php 7.1

I downgrade Cakephp from 3.5.6 to 3.5.0  and nothing :(

**Comment by ADmad** [comment] 2017-12-05 12:11
@Jonatanmdez PHP or CakePHP version shouldn't matter.

I haven't being able to reproduce the error you guys are reporting. Bake 1.5.4 works fine for me in a clean app as well as existing app.

**Comment by ADmad** [comment] 2017-12-05 12:25
@Jonatanmdez @keomaborges Try adding `Plugin::load('WyriHaximus/TwigView', ['bootstrap' => true]);` to your app's bootstrap.

**Comment by Jonatanmdez** [comment] 2017-12-05 20:43
Yep, thats works @ADmad  

With and without.
```php
jonatan@jonatan-probook:/var/www/html/dashboard$ bin/cake bake controller FbAdsAccounts

Baking controller class for FbAdsAccounts...

Creating file /var/www/html/dashboard/src/Controller/FbAdsAccountsController.php
Wrote `/var/www/html/dashboard/src/Controller/FbAdsAccountsController.php`
Bake is detecting possible fixtures...

Baking test case for App\Controller\FbAdsAccountsController ...

Creating file /var/www/html/dashboard/tests/TestCase/Controller/FbAdsAccountsControllerTest.php
Wrote `/var/www/html/dashboard/tests/TestCase/Controller/FbAdsAccountsControllerTest.php`
jonatan@jonatan-probook:/var/www/html/dashboard$ bin/cake bake controller FbAdsAccounts

Baking controller class for FbAdsAccounts...
Exception: Unexpected "element" tag (expecting closing tag for the "for" tag defined near line 55) in "/var/www/html/dashboard/vendor/cakephp/bake/src/Template/Bake/Controller/controller.twig" at line 55. in [/var/www/html/dashboard/vendor/twig/twig/lib/Twig/Parser.php, line 175]
```

But I don't understand the reason, I don't use the TwigView, is a CakePHP problem with old applications (My application was created with Cakephp 3.0.0)  or what?

**Comment by markstory** [comment] 2017-12-06 02:14
Bake Shell should be bootstrapping TwigView [here](https://github.com/cakephp/bake/blob/master/src/Shell/BakeShell.php#L59-L61).

**Comment by ADmad** [comment] 2017-12-06 03:54
@Jonatanmdez As of 1.5.0 bake uses twig. 

@markstory Yes it should, no idea why it doesn't for them.

**Comment by Jonatanmdez** [comment] 2017-12-06 09:43
I delete vendor and do composer update again, and same problem.

```
jonatan@jonatan-probook:/var/www/html/dashboard$ rm -rf vendor/*
jonatan@jonatan-probook:/var/www/html/dashboard$ composer update
Loading composer repositories with package information
    Authentication required (gitlabnew.qdqmedia.com):
      Username: ^C
jonatan@jonatan-probook:/var/www/html/dashboard$ composer update
Loading composer repositories with package information                                                                                                                                                         Updating dependencies (including require-dev)         Package operations: 124 installs, 0 updates, 0 removals
  - Installing cakephp/plugin-installer (1.0.0): Downloading (100%)         
  - Installing php-amqplib/php-amqplib (v2.6.2): Downloading (100%)         
  - Installing symfony/serializer (v3.4.1): Loading from cache
  - Installing webmozart/assert (1.2.0): Loading from cache
  - Installing phpdocumentor/reflection-common (1.0.1): Loading from cache
  - Installing phpdocumentor/type-resolver (0.4.0): Loading from cache
  - Installing phpdocumentor/reflection-docblock (3.3.2): Loading from cache
  - Installing psr/log (1.0.2): Loading from cache
  - Installing monolog/monolog (1.23.0): Downloading (100%)         
  - Installing psr/http-message (1.0.1): Loading from cache
  - Installing guzzlehttp/psr7 (1.4.2): Loading from cache
  - Installing guzzlehttp/promises (v1.3.1): Loading from cache
  - Installing guzzlehttp/guzzle (6.3.0): Loading from cache
  - Installing psr/cache (1.0.1): Downloading (100%)         
  - Installing firebase/php-jwt (v3.0.0): Downloading (100%)         
  - Installing google/auth (v1.1.0): Loading from cache
  - Installing googleads/googleads-php-lib (29.0.0): Downloading (100%)         
  - Installing zendframework/zend-diactoros (1.6.1): Loading from cache
  - Installing aura/intl (3.0.0): Downloading (100%)         
  - Installing cakephp/chronos (1.1.2): Downloading (100%)         
  - Installing cakephp/cakephp (3.5.7): Downloading (100%)         
  - Installing fheider/cakephp-datatables (dev-master d3bf1d3): Cloning d3bf1d382e from cache
  - Installing jonatanmdez/cakephp3-mandrill (dev-master f452542): Cloning f452542f62 from cache
  - Installing phpoffice/phpexcel (dev-master 049e85a): Cloning 049e85ae98 from cache
  - Installing holt59/cakephp3-bootstrap-helpers (dev-master 43e00d2): Cloning 43e00d23c7 from cache
  - Installing pgbi/cakephp3-soft-delete (dev-master 4670230): Cloning 4670230846 from cache
  - Installing facebook/php-ads-sdk (2.10.1): Downloading (100%)         
  - Installing thunderer/shortcode (dev-master 7678d04): Cloning 7678d04b95 from cache
  - Installing sentry/sentry (1.6.2): Downloading (100%)         
  - Installing mindscape/raygun4php (v1.8.0): Downloading (100%)         
  - Installing airbrake/phpbrake (v0.0.11): Downloading (100%)         
  - Installing bugsnag/bugsnag (v2.9.2): Downloading (100%)         
  - Installing jonatanmdez/php-error-handlers (dev-master 29914ab): Cloning 29914ab61d from cache
  - Installing optimiza/sauron-php-client (dev-master dbc0fd2): Cloning dbc0fd282b from cache
  - Installing ruflin/elastica (3.2.3): Downloading (100%)         
  - Installing cakephp/elastic-search (1.0.x-dev 548f729): Cloning 548f7292e2 from cache
  - Installing optimiza/wiggum (dev-master c8837b3): Cloning c8837b3d7d from cache
  - Installing skie/cakephp-phpstorm (dev-master 6864328): Cloning 6864328e9f from cache
  - Installing mobiledetect/mobiledetectlib (2.8.27): Loading from cache
  - Installing symfony/polyfill-mbstring (v1.6.0): Loading from cache
  - Installing symfony/yaml (v3.4.1): Loading from cache
  - Installing symfony/debug (v4.0.1): Loading from cache
  - Installing symfony/console (v3.4.1): Loading from cache
  - Installing symfony/filesystem (v4.0.1): Loading from cache
  - Installing symfony/config (v3.4.1): Loading from cache
  - Installing robmorgan/phinx (v0.8.1): Downloading (100%)         
  - Installing cakephp/migrations (1.7.1): Downloading (100%)         
  - Installing friendsofcake/search (3.2.0): Downloading (100%)         
  - Installing phpseclib/phpseclib (2.0.9): Loading from cache
  - Installing google/apiclient-services (v0.37): Loading from cache
  - Installing google/apiclient (v2.2.1): Loading from cache
  - Installing mandrill/mandrill (1.0.55): Downloading (100%)         
  - Installing mailchimp/mailchimp (2.0.6): Downloading (100%)         
  - Installing facebook/graph-sdk (5.6.1): Downloading (100%)         
  - Installing havokinspiration/wrench (1.0.2): Downloading (100%)         
  - Installing symfony/css-selector (v3.4.1): Loading from cache
  - Installing serps/core (v0.2.4): Downloading (100%)         
  - Installing serps/http-client-curl (v0.2.0): Downloading (100%)         
  - Installing serps/search-engine-google (v0.2.2): Downloading (100%)         
  - Installing phpwhois/phpwhois (v4.2.5): Downloading (100%)         
  - Installing intercom/intercom-php (v3.1.8): Loading from cache
  - Installing jeremyharris/cakephp-lazyload (1.0.3): Downloading (100%)         
  - Installing symfony/process (v4.0.1): Loading from cache
  - Installing nikic/php-parser (v3.1.2): Loading from cache
  - Installing symfony/polyfill-util (v1.6.0): Loading from cache
  - Installing symfony/polyfill-php56 (v1.6.0): Loading from cache
  - Installing jeremeamia/superclosure (2.3.0): Downloading (100%)         
  - Installing doctrine/lexer (v1.0.1): Loading from cache
  - Installing egulias/email-validator (2.1.3): Loading from cache
  - Installing swiftmailer/swiftmailer (v6.0.2): Loading from cache
  - Installing mtdowling/cron-expression (v1.2.1): Loading from cache
  - Installing hellogerard/jobby (v3.3.2): Loading from cache
  - Installing friendsofcake/cakephp-csvview (3.2.1): Loading from cache
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
  - Installing symfony/var-dumper (v3.4.1): Loading from cache
  - Installing psy/psysh (v0.8.15): Loading from cache
  - Installing jdorn/sql-formatter (v1.2.17): Downloading (100%)         
  - Installing symfony/finder (v4.0.1): Loading from cache
  - Installing seld/phar-utils (1.0.1): Downloading (100%)         
  - Installing seld/jsonlint (1.6.2): Loading from cache
  - Installing seld/cli-prompt (1.0.3): Downloading (100%)         
  - Installing justinrainbow/json-schema (5.2.6): Loading from cache
  - Installing composer/spdx-licenses (1.1.6): Downloading (100%)         
  - Installing composer/semver (1.4.2): Downloading (100%)         
  - Installing composer/ca-bundle (1.1.0): Loading from cache
  - Installing composer/composer (dev-master 578798c): Cloning 578798c87c from cache
  - Installing cakephp/debug_kit (3.11.2): Loading from cache
  - Installing sebastian/version (2.0.1): Loading from cache
  - Installing sebastian/resource-operations (1.0.0): Loading from cache
  - Installing sebastian/object-reflector (1.1.1): Loading from cache
  - Installing sebastian/recursion-context (3.0.0): Loading from cache
  - Installing sebastian/object-enumerator (3.0.3): Loading from cache
  - Installing sebastian/global-state (2.0.0): Loading from cache
  - Installing sebastian/exporter (3.1.0): Loading from cache
  - Installing sebastian/environment (3.1.0): Loading from cache
  - Installing sebastian/diff (2.0.1): Loading from cache
  - Installing sebastian/comparator (2.1.0): Loading from cache
  - Installing doctrine/instantiator (1.1.0): Loading from cache
  - Installing phpunit/php-text-template (1.2.1): Loading from cache
  - Installing phpunit/phpunit-mock-objects (5.0.4): Loading from cache
  - Installing phpunit/php-timer (1.0.9): Loading from cache
  - Installing phpunit/php-file-iterator (1.4.5): Loading from cache
  - Installing theseer/tokenizer (1.1.0): Loading from cache
  - Installing sebastian/code-unit-reverse-lookup (1.0.1): Loading from cache
  - Installing phpunit/php-token-stream (2.0.2): Loading from cache
  - Installing phpunit/php-code-coverage (5.2.4): Loading from cache
  - Installing phpspec/prophecy (1.7.3): Loading from cache
  - Installing phar-io/version (1.0.1): Loading from cache
  - Installing phar-io/manifest (1.0.1): Loading from cache
  - Installing myclabs/deep-copy (1.7.0): Loading from cache
  - Installing phpunit/phpunit (6.5.2): Loading from cache
  - Installing squizlabs/php_codesniffer (3.1.1): Loading from cache
  - Installing cakephp/cakephp-codesniffer (3.0.1): Downloading (100%)         
  - Installing twig/twig (v1.35.0): Loading from cache
  - Installing umpirsky/twig-php-function (v0.1): Loading from cache
  - Installing jasny/twig-extensions (v1.2.0): Loading from cache
  - Installing asm89/twig-cache-extension (1.3.2): Loading from cache
  - Installing aptoma/twig-markdown (2.0.0): Loading from cache
  - Installing ajgl/breakpoint-twig-extension (0.3.1): Loading from cache
  - Installing wyrihaximus/twig-view (4.2.0): Loading from cache
  - Installing cakephp/bake (1.5.4): Loading from cache
  - Installing dereuromark/cakephp-ide-helper (0.9.8): Loading from cache
```

I tried again deleting composer-cache and nothing, the same :(

**Comment by HoshangCharania** [comment] 2018-02-23 18:10
I was facing the same issue, I removed Plugin::loadAll(); and it started working fine. 

Any idea why does this happen?

**Comment by dereuromark** [comment] 2018-02-23 18:38
I looked into the code and now know why:
https://github.com/cakephp/bake/blob/master/src/Shell/BakeShell.php#L59-L61

Plugin::loadAll() loads the plugin, but wrong (without the bootstrap).
So you need either an adjusted loadAll() command, or omit it completely.

**Comment by ADmad** [comment] 2018-02-23 19:02
Closing as the docs have been updated clarifying how to ensure that TwigView's bootstrap is loaded.

**Closed by ADmad** 2018-02-23 19:02 UTC
Labels: On Hold
